function prcmap = calculate_invprctile(stack,event)
%
%
%   Function to calculate for each pixel the percentile of the coherence
%   timeseries. 
%
%	INPUTS:
%   	stack 			coherence stack generated by coherence_stack
%		event 			event coherence image
%
%	OUTPUTS:
%		prcmap 			GRIDobj containing the inverse percentile of
% 						the entire coherence time-series
%
%	This script uses the invprctile function Durga Lal Shresta
% 	available here: https://de.mathworks.com/matlabcentral/fileexchange/41131-inverse-percentiles-of-a-sample
%
%	S. Olen, 20.11.2019


% Loop through every pixel to calculate inverse percentile 
[ly,lx] = size(event.Z);
% Set aside the prcmap variable as GRIDobj to be filled
prcmap = event;
prcmap.Z = [];
for i = 1:ly
    for j = 1:lx
        try
            vec = stack.Z(i,j,:);
            vec = squeeze(vec);
            prcmap.Z(i,j) = invprctile(vec,event.Z(i,j));
        catch
            return
        end
    end
end


